<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="PublishAot;RuntimeIdentifier;SelfContained">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PublishAot>false</PublishAot>
    <RuntimeIdentifier></RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsPackable>false</IsPackable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../TheLithium.Imprint.Build/CompilerTypeFacts.cs" Link="CompilerTypeFacts.cs" />
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
