<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(ArtifactsPath)/obj/$(MSBuildProjectName)/generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup Condition="'$(UsePackageReferences)' != 'true'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)../src/TheLithium.Imprint.Core/TheLithium.Imprint.Core.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)../src/TheLithium.Imprint.Generator/TheLithium.Imprint.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" GlobalPropertiesToRemove="PublishAot;RuntimeIdentifier;SelfContained" />
    <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
    <CompilerVisibleProperty Include="MSBuildProjectName" />
  </ItemGroup>
  <ItemGroup Condition="'$(UsePackageReferences)' == 'true'">
    <PackageReference Include="TheLithium.Imprint" Version="$(Version)" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Shared/TestEnvironment.cs" Link="TestEnvironment.cs" />
  </ItemGroup>
</Project>
