<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAotCompatible>true</IsAotCompatible>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>imprint</ToolCommandName>
    <Description>Run any test runner with explicit Imprint snapshot update policies.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
